### ISSUE TITLE
The app used by my Navien boiler is not NaviLink, but Navien smart Tok, so I can't log in, can you support it?

### ISSUE THREAD

**Issue by zjczsl** [nikshriv/hass_navien_water_heater#1]

**Comment by nikshriv** [comment]
Navien Smart Tok is a separate api. This integration uses the unofficial Navilink api at https://github.com/rudybrian/PyNavienSmartControl

I don’t have any smart tok appliances, so I would not be able to develop and test support for it. It will probably require a separate integration. I think there is another api located at https://github.com/matthew1471/Navien-API that may support your appliance.
