### ISSUE TITLE
Navilink App Update and Authentication Change

### ISSUE THREAD

**Issue by megaz555** [nikshriv/hass_navien_water_heater#10]
It looks like Navien updated its Navilink app (forced update), which forced the change of authentication. You can no longer use an ID (only email address), and the password must be at least 10 characters long.

Because of this, the integration has failed and it no longer works. I tried to login, but it does not work. I am assuming the link to the authentication URL has changed.

In fact, I had to redo the whole WiFi setup on my Navien Navilink. Unfortunately, there is no way to go back, since you cannot downgrade the app. I tried to login with previous credentials, it does not work either.

Hope you can fix this sooner than later. Thank you!

**Comment by nikshriv** [comment]
Thanks, I’m aware of the problem. Tried to get my shower warm this morning and couldn't get it to turn on. It may take me a little while to get to it, but I'll look into it soon and hope to get the integration up and running again soon. Hopefully the only thing they changed is the authentication server.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Nasim Mansurov ***@***.***>
Sent: Tuesday, January 31, 2023 6:49:49 AM
To: nikshriv/hass_navien_water_heater ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nikshriv/hass_navien_water_heater] Navilink App Update and Authentication Change (Issue #10)


It looks like Navien updated its Navilink app (forced update), which forced the change of authentication. You can no longer use an ID (only email address), and the password must be at least 10 characters long.

Because of this, the integration has failed and it no longer works. I tried to login, but it does not work. I am assuming the link to the authentication URL has changed.

In fact, I had to redo the whole WiFi setup on my Navien Navilink. Unfortunately, there is no way to go back, since you cannot downgrade the app. I tried to login with previous credentials, it does not work either.

Hope you can fix this sooner than later. Thank you!

**Comment by nikshriv** [comment]
Unfortunately, Navien has completely changed the backend of the app. It now utilizes the AWS IOT MQTT platform. It's going to take me some time to figure out how to get this working again.

**Comment by tboyko** [comment]
Thanks for looking into this @nikshriv. Appreciate it!

**Comment by Desy10140** [comment]
I'm also available for testing.

Seems the credentials in their app are all borked as well. Even recovering your ID and password seems to fail.

**Comment by alexruffell** [comment]
> Unfortunately, Navien has completely changed the backend of the app. It now utilizes the AWS IOT MQTT platform. It's going to take me some time to figure out how to get this working again.

@nikshriv Is this a sign they may be taking integration of their product into smart homes more seriously or just locking it down? I seriously regret buying a Navien product from the smart home perspective... I think we should encourage all owners to complain to Navien requesting a formal API or method to integrate (Matter when supported?)

**Comment by Desy10140** [comment]
Matter support would be great and more likely.

**Comment by megaz555** [comment]
Quick update to everyone who is waiting for an update on this, and hoping for a fix.

Brian, who wrote the original PyNavienSmartControl Python library to connect to NaviLink confirmed that the change is indeed a major one, with v2 of the API being used. I tried to dig deeper into the API, but without the capability to generate an authentication token (they added it to v2), it is impossible to log into the API and see what commands are available and how they have changed. Someone would have to run a packet capture on an interface to see how the new NaviLink app talks to the new API, and if it is possible to authenticate against it. This is potentially going to be a very involved process, so it could take some time for Brian or someone else to come up with a solution. And in the meantime, we don't have hot water on demand :)

I have just implemented a solution that works really well, and it completely bypasses NaviLink. I will write it in detail in the next post for those who are interested, and who need a solution now.

Hope it helps the community. Thanks again to folks like Brian and @nikshriv for working on these projects. You guys are awesome!

**Comment by tboyko** [comment]
Wow, thank you for your dedication to this @nikshriv. Very impressive, particularly for an open source project.

**Comment by megaz555** [comment]
Here is a detailed, step-by-step process for running the hot water recirculation on demand in Home Assistant:

1) If you have an NPE unit like the NPE-180A2, 210A2 or 240A2, you should already have the PCB to be able to wire a hot button to your system. It looks like this (in red):

![Navien NPE PCB Hot Button](https://user-images.githubusercontent.com/24313201/217048381-8966d9c9-dc8e-4f72-b978-1e76871b814e.png)

Open up the cover of your water heater and see if the board is already there. If it is not there, you will need to buy the Navien "Hot Button Kit" part number PZZZ-00046. You can buy one from a Navien reseller like SuppliesDepot.com. I made the stupid mistake of buying it without checking my unit first, so I have an extra one that I have to return now (let me know if you are interested). Oh well, live and learn!

2) Once you confirm that you have the extra PCB in your unit, or you install it from the Hot Button kit, all you need to get now is a relay. You can use a WiFi or a Zwave relay - whatever works for your Home Assistant setup. Since I already have a Zwave network in my home, I decided to get the ZEN16 Zoos Multirelay: https://www.getzooz.com/zooz-zen16-multirelay/

I used this relay in the past to automate my fireplace, so I decided to use it for the Navien as well. The cool thing about the ZEN16 and the Navien NPE system, is that you can use power the ZEN16 through the Navien. All you need is 4 wires. I used a 22-gauge security alarm wire, which worked really well.

3) Turn off the Navien (use the power switch inside or unplug it from the outlet). To wire up the ZEN16 relay, use the 12V connector to connect to the + input on the ZEN16 (I used the red wire), and the GND connector under the same SIGNAL 1 to connect to the - input on the ZEN16. Then connect another wire to one of the connectors under SIGNAL 2 to one of the R1 connectors on the ZEN16. Connect the fourth wire to the second connector under SIGNAL 2 to the other one of the R1 connectors on the ZEN16 (it does not matter which one is which).

Double check the wires - you should have four wires connected in total. Once again, red wire (+) goes to the 12V, black wire (-) goes to the GND, two wires should be going from SIGNAL 2 to R1 on the ZEN16.

4) Turn on the Navien tankless water heater. You should see the blue light on the ZEN16 light up.

5) Add the ZEN16 to your Zwave network in Home Assistant. Make sure to click on the "Configure" link within Zwave controls of the device (under Device info) to configure the Multirelay. Set up the first switch (parameter 2) to be "Momentary" rather than a switch. I also went through parameter 6 (Relay 1: Auto Turno-Off Timer) and set it to 1, as well as parameter 7 (Relay 1: Auto Turn-Off Timer Unit) and set it to "Seconds", so that triggering the switch will only activate it for 1 second and then turn off immediately, imitating a button press.

6) If you have not previously configured your Navien with NaviLink to work with a Hot Button action, make sure to set all the right parameters within your unit. This will depend on the type of the tankless unit you have. It is easy to find out if you have it set up for the Hot Button - just use the new Navien app and see if you have a "Hot Button" link under "Control". If you don't see it, your Navien is set up for scheduled recirculation. You will need to modify it, so that it switches to Hot Button mode.

7) Now that the relay is up and running and fully configured, test it out in Home Assistant by manually triggering it. If it works, you will see the toggle turn on and immediately turn off, and your Navien should start the recirculation cycle.

8) If everything went well, all you need to do now is to add a button to your Home Assistant dashboard to trigger recirculation. The button will behave differently when compared to the NaviLink API. If previously, you had the button light up and keep the active color while recirculation is running, now it will light up and immediately turn off. It is a bit inconvenient, since you don't know when the cycle ends, but I know that it takes about 3 minutes for my home, so I just set up an automation to make a whole-house announcement through Sonos.

While this method has the above disadvantage, I find that it has one major advantage - it does not rely on the NaviLink system to be up and running, and it does not need WiFi to work. So if your Internet connection dies or Navien decides to do another abrupt update to its API, you are not left hanging.

I know this is not particularly relevant to the awesome work by this community (thank you @nikshriv once again for the hard work), but for those who need a working solution now, this is the only workaround that actually works.

**Comment by megaz555** [comment]
> I have already worked out the login process and the MQTT protocol that the new app uses. I will be rewriting Brian’s API this week. Hopefully should have it all working in a week or two. Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

That's excellent news. Thank you for the hard work. If you need someone to test anything out, let us know please!

**Comment by nikshriv** [comment]
Just to update everyone, I have successfully logged in to the AWS IOT server and receive MQTT status messages. Next, just need to get water heater control working. Should probably have the integration back up and running in the next week or so.

**Comment by tjstheiii** [comment]
If you would like any additional eyes nikshriv, maybe publish your current to a branch and let us know whats going on.  I'd be new to Home Assistant, but happy to look through and see if I can help. Perhaps do some testing, etc. I just got my unit the other week and got NaviLink working a few days ago.  If you're not interested in forks, thats quite alright and I will patiently wait (I doubt I would be able to figure out how to help before you finish anyhow)

**Comment by nikshriv** [comment]
An update...I have been struggling to get the integration working on HA. I have been using the AWSIoTPythonSDK package to connect to the AWS mqtt server that is the new backend of the app. The integration and I have been able to collect some data on the sensors, but when I restart HA, HA crashes with this error and it won't restart. The change is permanent and bricks the HA installation. Here is the error:

Exception has occurred: TypeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
unhashable type: 'list'
  File "/workspaces/core/homeassistant/helpers/entity_registry.py", line 398, in __setitem__
    self._index[(entry.domain, entry.platform, entry.unique_id)] = entry.entity_id
  File "/workspaces/core/homeassistant/helpers/entity_registry.py", line 953, in async_load
    entities[entity["entity_id"]] = RegistryEntry(
  File "/workspaces/core/homeassistant/helpers/entity_registry.py", line 1056, in async_load
    await hass.data[DATA_REGISTRY].async_load()
  File "/workspaces/core/homeassistant/bootstrap.py", line 241, in load_registries
    await asyncio.gather(
  File "/workspaces/core/homeassistant/bootstrap.py", line 262, in async_from_config_dict
    await load_registries(hass)
  File "/workspaces/core/homeassistant/bootstrap.py", line 152, in async_setup_hass
    await async_from_config_dict(config_dict, hass) is not None
  File "/workspaces/core/homeassistant/runner.py", line 146, in setup_and_run_hass
    hass = await bootstrap.async_setup_hass(runtime_config)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/workspaces/core/homeassistant/runner.py", line 179, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/workspaces/core/homeassistant/__main__.py", line 214, in main
    exit_code = runner.run(runtime_conf)
  File "/workspaces/core/homeassistant/__main__.py", line 226, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
TypeError: unhashable type: 'list'

If anyone has insight, please let me know. I am going to try to use the paho mqtt client instead and rewrite the api and integration again. I'll let you know when I've had more success.

**Comment by nikshriv** [comment]
The integration is done. Please download and give it a try. Let me know if you have any issues.

**Comment by kchiem** [comment]
> Here is a detailed, step-by-step process for running the hot water recirculation on demand in Home Assistant:
> ...

I did the same thing, but with a Shelly 1 (along with the temperature hat and temp probes so I can monitor exhaust, hot, and recirc pipe temperatures).  However, I've noticed one problem with this: when I trigger the hot button, it fires up the unit, but the unit shuts down seconds later, because the internal recirculation pump doesn't get activated--the hot outlet reaches temperature quickly while the recirc return stays cold.  When I set the recirculation mode on the Navien to something scheduled or always active, it does run the recirculation pump.  Have you confirmed the recirculation is actually working in the hot button mode?

**Comment by kchiem** [comment]
> The integration is done. Please download and give it a try. Let me know if you have any issues.

Hi Nik,

I was able to install it and it seems to be working.  The last question during setup asked how often I'd like to poll the hub.  So is this integration communicating with the hub directly, and not going through the cloud?

**Comment by Pelphry17** [comment]
> > The integration is done. Please download and give it a try. Let me know if you have any issues.
> 
> Hi Nik,
> 
> I was able to install it and it seems to be working. The last question during setup asked how often I'd like to poll the hub. So is this integration communicating with the hub directly, and not going through the cloud?
> 
> Edit: I just tried the hot button provided by it, but it doesn't seem to be doing anything.

Nik, Thanks for the work on this! 

Same issue here, everything except the Hot Button seems to be working. Hot Button status changes when activated in the Navien App, however it does not activate when turned on from HomeAssistant.

**Comment by matkam** [comment]
Just tried and it's missing the AWS root cert.

```
Logger: homeassistant.config_entries
Source: deps/lib/python3.10/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py:610 
First occurred: 7:24:02 AM (1 occurrences) 
Last logged: 7:24:02 AM

Error setting up entry navien for navien_water_heater
Traceback (most recent call last):
  File "/var/lib/hass/deps/lib/python3.10/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 608, in tls_set
    f = open(ca_certs, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/config/custom_components/navien_water_heater/cert/AmazonRootCA1.pem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/var/lib/hass/custom_components/navien_water_heater/__init__.py", line 20, in async_setup_entry
    await navilink.start()
  File "/var/lib/hass/custom_components/navien_water_heater/navien_api.py", line 49, in start
    await self.login()
  File "/var/lib/hass/custom_components/navien_water_heater/navien_api.py", line 95, in login
    return await self._get_device_list()
  File "/var/lib/hass/custom_components/navien_water_heater/navien_api.py", line 113, in _get_device_list
    await self._connect_aws_mqtt()
  File "/var/lib/hass/custom_components/navien_water_heater/navien_api.py", line 129, in _connect_aws_mqtt
    self.client.configureCredentials(self.aws_cert_path)
  File "/var/lib/hass/deps/lib/python3.10/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 246, in configureCredentials
    self._mqtt_core.configure_cert_credentials(cert_credentials_provider, cipher_provider)
  File "/var/lib/hass/deps/lib/python3.10/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 132, in configure_cert_credentials
    self._internal_async_client.set_cert_credentials_provider(cert_credentials_provider, ciphers_provider)
  File "/var/lib/hass/deps/lib/python3.10/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 79, in set_cert_credentials_provider
    self._paho_client.tls_set(ca_certs=ca_path, cert_reqs=ssl.CERT_REQUIRED, tls_version=ssl.PROTOCOL_SSLv23,
  File "/var/lib/hass/deps/lib/python3.10/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 610, in tls_set
    raise IOError(ca_certs+": "+err.strerror)
OSError: /config/custom_components/navien_water_heater/cert/AmazonRootCA1.pem: No such file or directory
```

**Comment by alexruffell** [comment]
@nikshriv Thank you so much for fixing it! While I live in the USA I set everything to metric as I am European. My set point and cumulative gas use are in metric units even though the water heater is set to the US system. The only entity that has the "Unit of measurement" setting which would allow me to easily switch from one system to another is the Cumulative Gas Use. 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/4006944/222972415-a8bdc0ce-715b-4406-96b4-a957d92afb56.png">

I was wondering whether it was possible to enable that setting for all entities so that I can switch them all to metric while leaving the heater on the US system. I am hoping it is something trivial like defining the unit of measurement as I do in ESPHome which then allows me to switch between C/F/K without any additional coding.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/4006944/222972798-90719fdf-b1bf-45ee-8f44-5e243e7daa15.png">

I'll investigate how to switch the heater to metric but adding the option to enable configuration may be handy too if easy to do.

**Comment by nikshriv** [comment]
Please start a new issue if you have something you would like to have addressed. It's easier to keep track that way. This issue will be closed.
