### ISSUE TITLE
My set point and cumulative gas use are in metric units eThe only entity that has the "Unit of measurement" setting which would allow me to easily switch from one system to another is the Cumulative Gas Use.

### ISSUE THREAD

**Issue by nikshriv** [nikshriv/hass_navien_water_heater#11]
@nikshriv Thank you so much for fixing it! While I live in the USA I set everything to metric as I am European. My set point and cumulative gas use are in metric units even though the water heater is set to the US system. The only entity that has the "Unit of measurement" setting which would allow me to easily switch from one system to another is the Cumulative Gas Use. 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/4006944/222972415-a8bdc0ce-715b-4406-96b4-a957d92afb56.png">

I was wondering whether it was possible to enable that setting for all entities so that I can switch them all to metric while leaving the heater on the US system. I am hoping it is something trivial like defining the unit of measurement as I do in ESPHome which then allows me to switch between C/F/K without any additional coding.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/4006944/222972798-90719fdf-b1bf-45ee-8f44-5e243e7daa15.png">

I'll investigate how to switch the heater to metric but adding the option to enable configuration may be handy too if easy to do.

_Originally posted by @alexruffell in https://github.com/nikshriv/hass_navien_water_heater/issues/10#issuecomment-1455137742_

**Comment by nikshriv** [comment]
> ```
>           @nikshriv Thank you so much for fixing it! While I live in the USA I set everything to metric as I am European. My set point and cumulative gas use are in metric units even though the water heater is set to the US system. The only entity that has the "Unit of measurement" setting which would allow me to easily switch from one system to another is the Cumulative Gas Use. 
> ```
> 
> <img alt="image" width="539" src="https://user-images.githubusercontent.com/4006944/222972415-a8bdc0ce-715b-4406-96b4-a957d92afb56.png">
> 
> I was wondering whether it was possible to enable that setting for all entities so that I can switch them all to metric while leaving the heater on the US system. I am hoping it is something trivial like defining the unit of measurement as I do in ESPHome which then allows me to switch between C/F/K without any additional coding.
> 
> <img alt="image" width="327" src="https://user-images.githubusercontent.com/4006944/222972798-90719fdf-b1bf-45ee-8f44-5e243e7daa15.png">
> 
> I'll investigate how to switch the heater to metric but adding the option to enable configuration may be handy too if easy to do.
> 
> _Originally posted by @alexruffell in [#10 (comment)](https://github.com/nikshriv/hass_navien_water_heater/issues/10#issuecomment-1455137742)_

The changes to the sensor unit of measurement that you're using are a Home Assistant feature. I didn't design the sensors to do that purposely. The sensors will present the unit of measurement based on how you set up your water heater. The easiest way to get all of your sensors to show up in metric is to change the setting on your water heater. This can't be done with the app or the integration, so you'll need to make the changes directly on your water heater. If the units don't change on HA after you make the change, it should change the next time you restart HA.

**Comment by alexruffell** [comment]
> The changes to the sensor unit of measurement that you're using are a Home Assistant feature. I didn't design the sensors to do that purposely. The sensors will present the unit of measurement based on how you set up your water heater. The easiest way to get all of your sensors to show up in metric is to change the setting on your water heater.

I realize that, but thought there was some easy way (like it is in ESPHome) to enable that by just defining what the entity is to HA so it knows to enable that HA feature. I had left the water heater configured with US system mostly because all the bills use those units so it is easier to compare but thinking about it I can do the math when needed, or just create templates in HA to automate it.

Thanks again for sharing your work on this integration!! You rock!

**Comment by nikshriv** [comment]
I made some changes to the sensor portion of the integration. It will now report all sensors in the same unit system. If your HA server is set for metric, all sensors will report in metric and the other way around. If you make a change to your preferred unit system in HA, you may have to reload the integration to get proper reporting of data.

**Comment by alexruffell** [comment]
You rock! Thank you!! I works great and is exactly what I was hoping for :)

<img width="298" alt="image" src="https://user-images.githubusercontent.com/4006944/225732603-7f9a79cf-d6bf-4d05-83f2-528e4ba26e8c.png">
