### ISSUE TITLE
Timer on Connection Error

### ISSUE THREAD

**Issue by megaz555** [nikshriv/hass_navien_water_heater#14]
@nikshriv,

Once again, thank you for fixing this integration! I am opening a separate issue request (which I hope you don't mind), for the case when the connection to Navilink from the integration fails. It looks like when the connection is unreachable, the integration does not generate a stop error, making the entity unavailable - it just keeps on trying, queuing all the requests to the unit.

I think it would be a good idea to move the entity to "unavailable" state when the connection to Navilink fails. Perhaps poll it again and retry, and if the connection fails again, keep it as "unavailable", and only switch back to available when the connection succeeds. This way, we can perform automations based on the state of the entity (i.e. use conditionals to show the button if the connection is up).

Hope this makes sense. Thanks once again!

**Comment by nikshriv** [comment]
Good suggestion. I incorporated that into the next version. Will release after updating a few more things.

**Comment by megaz555** [comment]
Awesome! Looking forward to seeing it, thank you!

**Comment by nikshriv** [comment]
This is fixed with latest update. Entities should become unavailable when the integration loses it's connection to the AWS IOT server.
