### ISSUE TITLE
Navilink app "Operating Capacity" and integration "CH1 Heating Capacity" discrepancy

### ISSUE THREAD

**Issue by kchiem** [nikshriv/hass_navien_water_heater#15]
I just noticed that these two values seem to be in a ratio of 1:2 from each other.  For instance, the app is telling me that the Operating Capacity is 27.0% at the moment, while the integration is saying that the CH1 Heating Capacity is 54%.  Is this some sort of division bug?  Shouldn't these two be the same?

**Comment by nikshriv** [comment]
Is your water heater in metric mode? If so, that is entirely possible. They use a factor of 2 when reporting temperature in metric units. It's possible they may be doing the same for the operating power.

**Comment by kchiem** [comment]
I don't think so?  All my temperature measurements are in F.

**Comment by Carlyle05** [comment]
i have the same issue, fresh setup of integration

**Comment by nikshriv** [comment]
What model do you have? I suppose it could be the model you have reports this differently than the model I have. Mine is NPE2 and the heating capacity is being reported correctly.

**Comment by kchiem** [comment]
NPE-240A2

**Comment by nikshriv** [comment]
If you want to help debug, go to this repository and clone it to your computer: https://github.com/nikshriv/navilink_api. Follow the instructions and run test_connect.py

Please copy and post your results here. I will take a look and see if I can figure out what's going on. Thanks

**Comment by kchiem** [comment]
```
Channel Info:
{'unitType': 11, 'unitCount': 1, 'temperatureType': 2, 'setupDHWTempMin': 97, 'setupDHWTempMax': 185, 'setupHeatTempMin': 32, 'setupHeatTempMax': 32, 'onDemandUse': 1, 'heatControl': 1, 'wwsd': 2, 'commercialLock': 2, 'recirculationUse': 2, 'highTempDHWUse': 0, 'reCirculationSetupTempMin': 32, 'reCirculationSetupTempMax': 32, 'panelDipSwitchInfo': 0, 'mainDipSwitchInfo': 8192, 'DHWTankSensorUse': 2, 'DHWUse': 2}

Channel Status:
{'unitCount': 1, 'unitType': 11, 'operationUnitCount': 0, 'weeklyControl': 2, 'totalDayCount': 0, 'avgCalorie': 0, 'heatSettingTemp': 0, 'powerStatus': True, 'heatStatus': 2, 'onDemandUseFlag': False, 'avgOutletTemp': 108, 'avgInletTemp': 101, 'avgSupplyTemp': 32, 'avgReturnTemp': 32, 'recirculationSettingTemp': 0, 'outdoorTemperature': 0, 'unitInfo': {'unitNumberStart': 1, 'unitNumberEnd': 1, 'unitStatusList': [{'unitNumber': 1, 'controllerVersion': 3074, 'panelVersion': 5376, 'errorCode': 0, 'subErrorCode': 0, 'gasInstantUsage': 0.0, 'accumulatedGasUsage': 1363.1, 'currentOutletTemp': 108, 'currentInletTemp': 101, 'currentSupplyTemp': 32, 'currentReturnTemp': 32, 'currentRecirculationTemp': 0, 'currentOutputTDSValue': 0, 'accumulatedWaterUsage': 0, 'daysFilterUsed': 0, 'filterChange': 0, 'DHWFlowRate': 0.0, 'PoEStatus': 0, 'CIPSolutionRemained': 0, 'CIPStatus': 0, 'CIPOperationTimeHour': 0, 'CIPOperationTimeMin': 0, 'CIPSolutionSupplement': 0}]}, 'DHWSettingTemp': 118}

Channel Status:
{'unitCount': 1, 'unitType': 11, 'operationUnitCount': 0, 'weeklyControl': 2, 'totalDayCount': 0, 'avgCalorie': 0, 'heatSettingTemp': 0, 'powerStatus': True, 'heatStatus': 2, 'onDemandUseFlag': False, 'avgOutletTemp': 108, 'avgInletTemp': 101, 'avgSupplyTemp': 32, 'avgReturnTemp': 32, 'recirculationSettingTemp': 0, 'outdoorTemperature': 0, 'unitInfo': {'unitNumberStart': 1, 'unitNumberEnd': 1, 'unitStatusList': [{'unitNumber': 1, 'controllerVersion': 3074, 'panelVersion': 5376, 'errorCode': 0, 'subErrorCode': 0, 'gasInstantUsage': 0.0, 'accumulatedGasUsage': 1363.1, 'currentOutletTemp': 108, 'currentInletTemp': 101, 'currentSupplyTemp': 32, 'currentReturnTemp': 32, 'currentRecirculationTemp': 0, 'currentOutputTDSValue': 0, 'accumulatedWaterUsage': 0, 'daysFilterUsed': 0, 'filterChange': 0, 'DHWFlowRate': 0.0, 'PoEStatus': 0, 'CIPSolutionRemained': 0, 'CIPStatus': 0, 'CIPOperationTimeHour': 0, 'CIPOperationTimeMin': 0, 'CIPSolutionSupplement': 0}]}, 'DHWSettingTemp': 118}

Channel Status:
{'unitCount': 1, 'unitType': 11, 'operationUnitCount': 0, 'weeklyControl': 2, 'totalDayCount': 0, 'avgCalorie': 0, 'heatSettingTemp': 0, 'powerStatus': True, 'heatStatus': 2, 'onDemandUseFlag': False, 'avgOutletTemp': 107, 'avgInletTemp': 100, 'avgSupplyTemp': 32, 'avgReturnTemp': 32, 'recirculationSettingTemp': 0, 'outdoorTemperature': 0, 'unitInfo': {'unitNumberStart': 1, 'unitNumberEnd': 1, 'unitStatusList': [{'unitNumber': 1, 'controllerVersion': 3074, 'panelVersion': 5376, 'errorCode': 0, 'subErrorCode': 0, 'gasInstantUsage': 0.0, 'accumulatedGasUsage': 1363.1, 'currentOutletTemp': 107, 'currentInletTemp': 100, 'currentSupplyTemp': 32, 'currentReturnTemp': 32, 'currentRecirculationTemp': 0, 'currentOutputTDSValue': 0, 'accumulatedWaterUsage': 0, 'daysFilterUsed': 0, 'filterChange': 0, 'DHWFlowRate': 0.0, 'PoEStatus': 0, 'CIPSolutionRemained': 0, 'CIPStatus': 0, 'CIPOperationTimeHour': 0, 'CIPOperationTimeMin': 0, 'CIPSolutionSupplement': 0}]}, 'DHWSettingTemp': 118}

Channel Status:
{'unitCount': 1, 'unitType': 11, 'operationUnitCount': 0, 'weeklyControl': 2, 'totalDayCount': 0, 'avgCalorie': 0, 'heatSettingTemp': 0, 'powerStatus': True, 'heatStatus': 2, 'onDemandUseFlag': False, 'avgOutletTemp': 107, 'avgInletTemp': 100, 'avgSupplyTemp': 32, 'avgReturnTemp': 32, 'recirculationSettingTemp': 0, 'outdoorTemperature': 0, 'unitInfo': {'unitNumberStart': 1, 'unitNumberEnd': 1, 'unitStatusList': [{'unitNumber': 1, 'controllerVersion': 3074, 'panelVersion': 5376, 'errorCode': 0, 'subErrorCode': 0, 'gasInstantUsage': 0.0, 'accumulatedGasUsage': 1363.1, 'currentOutletTemp': 107, 'currentInletTemp': 100, 'currentSupplyTemp': 32, 'currentReturnTemp': 32, 'currentRecirculationTemp': 0, 'currentOutputTDSValue': 0, 'accumulatedWaterUsage': 0, 'daysFilterUsed': 0, 'filterChange': 0, 'DHWFlowRate': 0.0, 'PoEStatus': 0, 'CIPSolutionRemained': 0, 'CIPStatus': 0, 'CIPOperationTimeHour': 0, 'CIPOperationTimeMin': 0, 'CIPSolutionSupplement': 0}]}, 'DHWSettingTemp': 118}
Connection to Navilink server lost
```

**Comment by kchiem** [comment]
PS.  Might want to add a requirements.txt with

```
aiohttp==3.8.4
AWSIoTPythonSDK==1.5.2
```

.. in that repository.

**Comment by kchiem** [comment]
BTW, it seems that since I ran this, the HA integration stopped updating.

**Comment by kchiem** [comment]
Restarting HA got it working again, but it stopped working again tonight.  Is this the integration losing connection to the AWS servers and not reconnecting automatically?

**Comment by tjstheiii** [comment]
> Restarting HA got it working again, but it stopped working again tonight. Is this the integration losing connection to the AWS servers and not reconnecting automatically?

For what it's worth, my NaviLink app is saying it can't connect to the servers at the top when I'm starting it this morning.

**Comment by kchiem** [comment]
> For what it's worth, my NaviLink app is saying it can't connect to the servers at the top when I'm starting it this morning.

For me, when I noticed the graphed values unchanging for hours, restarting HA fixed it both times.

**Comment by nikshriv** [comment]
Yes, I’m finding the same problem. It occurs after 24 hours. The server closes the connection after 24 hours. I thought I had it handled, but it looks like I need to figure out what’s going wrong in the reconnection process. For now, instead of restarting HA, you can just reload the integration from the devices & services section of HA

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tjstheiii** [comment]
Is the new auth token just expiring?

**Comment by bdriscoll** [comment]
I'm having the same issue.  restart/reload gets it working again.

**Comment by nikshriv** [comment]
I am uploading an update that should take care of the reconnection issue. In the latest update, the integration will disconnect and reconnect to the AWS server to refresh the connection at 2am. Please test and let me know if this is working for you. If working, I will add a configuration option to customize the refresh time.

**Comment by kchiem** [comment]
The disconnection problem seems to be fixed, as it's been running with your update for the past few days without stalling.

But.. the 1:2 ratio problem for which this issue was opened still exists.  :)

**Comment by kchiem** [comment]
I take back what I said about the disconnect problem.  Just found it stuck again.

**Comment by nikshriv** [comment]
Yes, you are right. It looks like the number reported for operating capacity is at a 1:2 ratio. That's a quick change. Should have it fixed soon.

Regarding the connection issue, do you have the latest version installed? I've made a couple of changes recently that fixed a problem with reconnecting in the instance of your router rebooting or losing its connection to the internet.

**Comment by kchiem** [comment]
> Regarding the connection issue, do you have the latest version installed?

Version 35cf5fb

**Comment by nikshriv** [comment]
Check your log for errors and warnings for the navien integration and post here.

**Comment by kchiem** [comment]
```
This error originated from a custom integration.

Logger: AWSIoTPythonSDK.core.protocol.mqtt_core
Source: custom_components/navien_water_heater/navien_api.py:208
Integration: Navien NaviLink Water Heater Integration (documentation)
First occurred: 10:16:45 AM (1 occurrences)
Last logged: 10:16:45 AM

Publish timed out
```

**Comment by nikshriv** [comment]
Both issues fixed in the latest update. Please download and try again.

**Comment by kchiem** [comment]
Updated to 94ba3a4.

**Comment by kchiem** [comment]
The titled issue appears to be fixed.  It's been 3 days and so far, no disconnects either.
