### ISSUE TITLE
Does this work with NaviLink Lite?

### ISSUE THREAD

**Issue by mediacutlet** [nikshriv/hass_navien_water_heater#16]
Thanks for the awesome integration. I recently had a Navien NCB-240/130H installled and have been eyeing the [NaviLink Lite](https://www.navieninc.com/downloads/navilink-lite-wi-fi-control-spec-sheet-en) as an upgrade. I believe the 'Lite' version is new but uses the same app. Does anyone know if this works with [NaviLink Lite](https://www.navieninc.com/downloads/navilink-lite-wi-fi-control-spec-sheet-en)?

**Comment by nikshriv** [comment]
Not sure about this. I didn't know they released a new device until now. If it uses the same app, there's a chance it may work just fine with this integration. I would suggest you try installing the integration and see if it works. Let me know how it goes.

**Comment by mediacutlet** [comment]
I've had some trouble finding this unit since it is so new but finally was able to order one. It should be in my hands next week, I'll report back.

**Comment by mediacutlet** [comment]
Confirmed, this works with Navilink Lite!

![Navien-Navilink-Lite-2023-03-28 172554](https://user-images.githubusercontent.com/26329687/228370646-332f9215-3513-48bd-a75a-bf361e5f8e5f.jpg)

**Comment by nikshriv** [comment]
Nice!
