### ISSUE TITLE
Request: Open Discussions for Repo

### ISSUE THREAD

**Issue by FormerLurker** [nikshriv/hass_navien_water_heater#17]
First off, great work!

I'm wondering if you'd be willing to turn on discussions for this repo.  I have an NFC-250/200H combination boiler/water heater, and have been capturing additional channel info and status messages in an attempt to add additional controls/information for the boiler part of the system.  Since you don't seem to be using a combination boiler, I don't see this as something that belongs in the issues as a request, but rather a discussion that may turn into a pull request.  I understand if this isn't something you care to do.

Thank you for your time and effort here!

**Comment by FormerLurker** [comment]
Well, I took a stab at it, and though it needs some refinement, here's what I came up with:

![image](https://user-images.githubusercontent.com/33363128/227085970-46394bde-ca5c-45b3-8f3a-ac80d6f1074f.png)

I added some information about the supported device types that I looked up (Boiler/Water Heater/Combi Boiler) and added a few sensors based on that.  The heat switch is based on the reported capabilities of the unit.

Also, away mode shuts off the boiler power, killing DHW and heat, though most units have freeze protection.  That may need some slight tweaks in the case of my particular combi-boiler.

I've also been having some 'ignition errors' (it's a new install, still has some bugs) and may try to add a sensor for general error reporting.  Would be nice to get a notification if my boiler is locked out!

Lastly, the 'heat' button doesn't work, because I don't know the command id.  I'm guessing I'll have to add a proxy and do a man-in-the-middle?  Hopefully no manual apk patches will be necessary, as I've seen in the past.

Anyway, I'll try to put some finesse on it and send you a PR once I push the code to Github.  So far I've just been editing it in Studio Code Server, lol!  

Let me know if you have any comments/suggestions.

**Comment by mediacutlet** [comment]
Thanks for kicking this off! I too have a similar combi unit and would love the additional sensor values. Cheers!

**Comment by nikshriv** [comment]
Nice work...I would be happy to take a look at your modifications and incorporate. It would be nice to have full support for combi-boilers, but as you pointed out, I don't have one so I have not been able to test it. I did use the "man-in-the-middle" approach to find the commands, and fortunately didn't even need to patch the app.
