### ISSUE TITLE
Help getting this installed

### ISSUE THREAD

**Issue by Glen-Hart** [nikshriv/hass_navien_water_heater#2]
Hi,

I have managed to download this in HACS, then restarted.

I am not seeing it in the HA Integration nor as any device or entity. 

If you can provide me with some guidance please.

**Comment by nikshriv** [comment]
Did you close and restart your browser window as well? Usually you have to do this to update the integration list in HA when installing an integration from HACS.

**Comment by Glen-Hart** [comment]
Hi,

Thank you for your responds and most importantly  developing this integration.
I just check it, after my PC rebooted over night and it was there.

Sorry for wasting your time. There is so much to learn and I am relatively new.

Glen.
