### ISSUE TITLE
Source: custom_components/navien_water_heater/__init__.py:27 

### ISSUE THREAD

**Issue by tayloracarr** [nikshriv/hass_navien_water_heater#3]
After the latest update I'm getting the below error. Is this something on my end I need to adjust?

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/navien_water_heater/__init__.py", line 27, in async_setup_entry
    navilink = NavienSmartControl(entry.data["username"],entry.data["gatewayID"],polling_mode = True)
KeyError: 'gatewayID'

**Comment by nikshriv** [comment]
Sorry about that. Trying to make some changes to the underlying navien_api and switched the default repository to dev. I will change it back while I am working on these changes.

**Comment by tayloracarr** [comment]
> Sorry about that. Trying to make some changes to the underlying navien_api and switched the default repository to dev. I will change it back while I am working on these changes.

All good!! Thank you so much for making the integration.

**Comment by tayloracarr** [comment]
This one is back after the latest update.

Logger: homeassistant.config_entries
Source: custom_components/navien_water_heater/__init__.py:27 
Integration: Navien NaviLink Water Heater Integration ([documentation](https://www.github.com/nikshriv/hass_navien_water_heater)) 
First occurred: 2:22:06 PM (1 occurrences) 
Last logged: 2:22:06 PM

Error setting up entry navien_[MY USERNAME] for navien_water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/navien_water_heater/__init__.py", line 27, in async_setup_entry
    navilink = NavienSmartControl(entry.data["username"],entry.data["gatewayID"])
KeyError: 'gatewayID'

**Comment by nikshriv** [comment]
In my previous version, I was creating devices for all NaviLink hubs in a person's account. For efficiency reasons, I recently changed the integration to only allow one hub per config entry, and that is the source of your problem. You will need to delete the integration and reinstall. The configuration during setup will ask you to select the hub you want to set up and then it will ask you for a polling interval. I would leave the default of 15 seconds. It should work after that, and I don't plan for any more breaking changes.

**Comment by tayloracarr** [comment]
> In my previous version, I was creating devices for all NaviLink hubs in a person's account. For efficiency reasons, I recently changed the integration to only allow one hub per config entry, and that is the source of your problem. You will need to delete the integration and reinstall. The configuration during setup will ask you to select the hub you want to set up and then it will ask you for a polling interval. I would leave the default of 15 seconds. It should work after that, and I don't plan for any more breaking changes.

Worked out exactly as stated. Thank you for making this integration!!

**Comment by tayloracarr** [comment]
Closing
