### ISSUE TITLE
This integration crashes HA 2024.4.x

### ISSUE THREAD

**Issue by kchiem** [nikshriv/hass_navien_water_heater#39]
@bdraco has some guidance on fixes needed here: 

https://discord.com/channels/330944238910963714/332167321311510530/1227118274056028241

https://discord.com/channels/330944238910963714/332167321311510530/1227153206883389480

https://discord.com/channels/330944238910963714/1227155975518027839

But this is all out of my league.  Can someone else that understands this integration tackle this?

**Comment by kchiem** [comment]
@bakerkj @KenReneris ?

**Comment by bakerkj** [comment]
Hi @kchiem,

I have not been seeing any errors like the one you pointed to above on those discord threads. My system running HA `2024.4.3`. 

I did however take a stab at using @bdraco's suggested fixes. I pushed them here (https://github.com/bakerkj/hass_navien_water_heater/compare/main...bakerkj:hass_navien_water_heater:bakerkj/fix-async-threadsafe?expand=1). I am running my system with these changes now, without issue.

You are welcome to try to run these changes on your system as well. 

Assuming these changes work fine, I'll merge these change to my own `main` branch in a day or two.

**Comment by kchiem** [comment]
Hi Ken,

Thanks for taking this.  I was getting the errors as mentioned in the links above, but just re-upgraded back to 2024.4.3 after having switched to this branch:

https://github.com/asheliahut/hass_navien_water_heater

And I'm not seeing the errors anymore.  I suspect this change might have fixed the errors:

https://github.com/nikshriv/hass_navien_water_heater/pull/25/commits/abc2e791c1901875766d0ef65f1617ca22b01163

Are you running with that change already?

**Comment by bakerkj** [comment]
@kchiem, that is good news. If I understood @bdraco assessment, I think  https://github.com/nikshriv/hass_navien_water_heater/commit/abc2e791c1901875766d0ef65f1617ca22b01163 fixes half of the issue. Maybe it is the more common issue?

I can go ahead and merge my change to my branch. Would you be willing to give it a try?

**Comment by kchiem** [comment]
> Would you be willing to give it a try?

Just switched to your branch.  Will let you know if I see anything come up.

**Comment by bakerkj** [comment]
@kchiem is it still working for you?

**Comment by kchiem** [comment]
> @kchiem is it still working for you?

Yes, I haven't seen any errors from it on 2024.4.3.

**Comment by GitHubGoody** [comment]
@bakerkj Thank you for taking this integration on! I'm back up and running after a couple weeks of no updates from NaviLink. I'll let you know if any issues arise as well.

**Comment by bakerkj** [comment]
I am happy to help!
