### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by megaz555** [nikshriv/hass_navien_water_heater#7]
First of all, thank you so much for writing this component! I have a Navien NPE2-240A2 and I just got NaviLink up and running, with the hopes that I could get this integration going. Unfortunately, after I get it installed, I get an integration error, with the following logs:

2022-07-28 09:14:29 ERROR (MainThread) [custom_components.navien_water_heater.navien_api] AttributeError: 'NoneType' object has no attribute 'get'
2022-07-28 09:14:29 ERROR (MainThread) [custom_components.navien_water_heater] KeyError: 'channel'
2022-07-28 09:15:51 ERROR (MainThread) [custom_components.navien_water_heater] KeyError: 'channel'
2022-07-28 09:17:12 ERROR (MainThread) [custom_components.navien_water_heater] KeyError: 'channel'
2022-07-28 09:18:34 ERROR (MainThread) [custom_components.navien_water_heater] KeyError: 'channel'
2022-07-28 09:20:01 ERROR (MainThread) [custom_components.navien_water_heater] KeyError: 'channel'
2022-07-28 09:21:22 ERROR (MainThread) [custom_components.navien_water_heater] KeyError: 'channel'
2022-07-28 09:22:43 ERROR (MainThread) [custom_components.navien_water_heater] KeyError: 'channel'
2022-07-28 09:24:03 ERROR (MainThread) [custom_components.navien_water_heater] KeyError: 'channel'
2022-07-28 09:25:24 ERROR (MainThread) [custom_components.navien_water_heater] KeyError: 'channel'
2022-07-28 09:26:44 ERROR (MainThread) [custom_components.navien_water_heater.navien_api] AttributeError: 'NoneType' object has no attribute 'get'

I tried to do basic troubleshooting, but sadly, I couldn't get anywhere. This component fails upon __init.py__ after it attempts to get the channel number? I tried to change the channel from 1 to 2, and I tried a bunch of other stuff to no avail. Login and pass are correct, integration is able to pull my gateway name and all, so it is working partially.

Thanks for your help, it is truly appreciated!

**Comment by rudybrian** [comment]
@megaz555 what port on the Navilink is your NPE2-240A2 plugged in to? The error suggests that the Navilink (gateway) doesn't see anything plugged in to one of the three RS485 ports. You might want to try running _NavienSmartControl-CLI.py -summary_ from [rudybrian/PyNavienSmartControl](https://github.com/rudybrian/PyNavienSmartControl) and let me know what it shows under Channel Info (see [here](https://github.com/rudybrian/PyNavienSmartControl/issues/18) for examples of what the output should look like)

**Comment by megaz555** [comment]
Brian, I do have it plugged into the first com port. Since I saw the error and thought something might be wrong with the port, I even tried to change it to port 2 (middle one) to no avail.

I will try to run the CLI.py later today and see what the output is. Thanks so much for your help - hopefully the CLI will reveal the issue.

**Comment by megaz555** [comment]
Brian,

Here is the output:

python3 NavienSmartControl-CLI.py -channel 2 -summary
--------------
Navien-API V1.0
--------------

---------------------------
Device ID: 8472072d366a13fb
Nickname: Navien
State: 1
Connected: 7/30/2022 12:02:50 AM
Server IP Address: X.X.X.X
Server TCP Port Number: 6001
---------------------------

Channel Info
---------------------------
Channel:1
	Device Model Type: NO_DEVICE
	Device Count: 0
	Temp Flag: CELSIUS
	Minimum Setting Water Temperature: 0
	Maximum Setting Water Temperature: 0
	Heating Minimum Setting Water Temperature: 0
	Heating Maximum Setting Water Temperature: 0
	Use On Demand: UNKNOWN
	Heating Control: SUPPLY
	wwsdFlag: OK
	commercialLock: OK
	hotwaterPossibility: OFF
	recirculationPossibility: OFF
	High Temperature: TEMPERATURE_60
	Use Warm Water: OFF
Channel:2
	Device Model Type: NPE2
	Device Count: 1
	Temp Flag: FAHRENHEIT
	Minimum Setting Water Temperature: 97
	Maximum Setting Water Temperature: 185
	Heating Minimum Setting Water Temperature: 32
	Heating Maximum Setting Water Temperature: 32
	Use On Demand: WARMUP
	Heating Control: SUPPLY
	wwsdFlag: OK
	commercialLock: OK
	hotwaterPossibility: OFF
	recirculationPossibility: OFF
	High Temperature: TEMPERATURE_60
	Use Warm Water: ON
Channel:3
	Device Model Type: NO_DEVICE
	Device Count: 0
	Temp Flag: CELSIUS
	Minimum Setting Water Temperature: 0
	Maximum Setting Water Temperature: 0
	Heating Minimum Setting Water Temperature: 0
	Heating Maximum Setting Water Temperature: 0
	Use On Demand: UNKNOWN
	Heating Control: SUPPLY
	wwsdFlag: OK
	commercialLock: OK
	hotwaterPossibility: OFF
	recirculationPossibility: OFF
	High Temperature: TEMPERATURE_60
	Use Warm Water: OFF
---------------------------


Channel 2 Info:
Device: 1
State
---------------------------
Controller Version: 779
Panel Version: 19
Device Model Type: NPE2
Device Count: 1
Current Channel: 2
Device Number: 1
Error Code: Normal
Operation Device Number: 1
Average Calorimeter: 41.0 %
Current Gas Usage: 68079.0 BTU
Total Gas Usage: 4234.2 ft³
Hot Water Setting Temperature: 125 °F
Hot Water Current Temperature: 105 °F
Hot Water Flow Rate: 2.9 GPM
Inlet Temperature: 72 °F
Power Status: ON
Heat Status: OFF
Use On Demand: OFF
Weekly Control: ON
Day Sequences
	SUN
		Hour: 8, Minute: 0, ON
		Hour: 10, Minute: 0, OFF
	MON
		None
	TUE
		None
	WED
		None
	THU
		Hour: 12, Minute: 0, ON
		Hour: 13, Minute: 0, OFF
		Hour: 22, Minute: 20, ON
		Hour: 23, Minute: 0, OFF
	FRI
		Hour: 5, Minute: 0, ON
		Hour: 6, Minute: 0, OFF
		Hour: 10, Minute: 50, ON
		Hour: 11, Minute: 10, OFF
	SAT
		None
---------------------------


Done

**Comment by megaz555** [comment]
From what I can see, everything appears to be in order. But the HA integration refuses to work, even though all credentials and other info are correct. It pulls the name of the device without any issues either, just gives a bunch of errors upon start...

**Comment by rudybrian** [comment]
Hmm, this looks fine. Will need @nikshriv to weigh in as it seems to be something to do with the HA plugin not setting the channel when querying the device via the SmartControl protocol Python module.

**Comment by megaz555** [comment]
Brian, thanks for the response. Has the integration been working for you?

I am thinking if perhaps my NaviLink is different than what the integration was made for?

**Comment by megaz555** [comment]
To anyone who experiences this problem - it seems like the code requires some data before it starts working. After letting the NaviLink device for a few days and deleting / adding the integration into HA, it started working!

**Comment by alexruffell** [comment]
I might be having the same issue. Everything was working, then it started.

```
This error originated from a custom integration.

Logger: custom_components.navien_water_heater.navien_api
Source: custom_components/navien_water_heater/navien_api.py:707
Integration: Navien NaviLink Water Heater Integration (documentation)
First occurred: August 10, 2022 at 05:52:25 (53 occurrences)
Last logged: 09:07:52

TimeoutError:
Connection reset by Navien server, reconnecting...
TimeoutError: This error occurred while attempting to reconnect to Navien server
AttributeError: 'NoneType' object has no attribute 'get'
```

I'll try to remove the integration and add it back.
