### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connect call failed ('52.23.151.44', 6001) This error occurred while attempting to reconnect to Navien server - 40k occurrences!

### ISSUE THREAD

**Issue by alexruffell** [nikshriv/hass_navien_water_heater#8]
I just noticed that I have about 40k occurrences of an error related to the Navien integration. Also, it complains it cannot connect to an Amazon IP. Why is it connecting to it in the first place? Who owns that service running on AWS?

Any chance of keeping this integration local?

<img width="794" alt="image" src="https://user-images.githubusercontent.com/4006944/194789032-8253b5b1-35df-46ec-861a-69428324f3c0.png">

```
This error originated from a custom integration.

Logger: custom_components.navien_water_heater.navien_api
Source: custom_components/navien_water_heater/navien_api.py:242
Integration: Navien NaviLink Water Heater Integration (documentation)
First occurred: 19:42:32 (38609 occurrences)
Last logged: 20:29:17

ConnectionRefusedError: [Errno 111] Connect call failed ('52.23.151.44', 6001) This error occurred while attempting to reconnect to Navien server
TimeoutError: This error occurred while attempting to reconnect to Navien server
```

Not sure whether this is related but looking around I also found this:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/4006944/194789268-f6552ba1-c3d2-461b-8e3a-80cf79dcea5a.png">

**Comment by nikshriv** [comment]
I had the same thing happen today as well. I think the Navilink server must be down. I can no longer connect my Navilink to my Wi-Fi. I called customer support, but they seemed completely unaware that there is a problem.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: alexruffell ***@***.***>
Sent: Sunday, October 9, 2022 6:34:40 PM
To: nikshriv/hass_navien_water_heater ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nikshriv/hass_navien_water_heater] ConnectionRefusedError: [Errno 111] Connect call failed ('52.23.151.44', 6001) This error occurred while attempting to reconnect to Navien server - 40k occurrences! (Issue #8)


I just noticed that I have about 40k occurrences of an error related to the Navien integration. Also, it complains it cannot connect to an Amazon IP. Why is it connecting to it in the first place? Who owns that service running on AWS?

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F4006944%2F194789032-8253b5b1-35df-46ec-861a-69428324f3c0.png&data=05%7C01%7C%7C8c52c529787d4450e5f508daaa5f9b15%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638009624850484370%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ftl5JIvcJsoKr6Bpm63yIXXOMo5y%2FL0P5mVBQXh4J3g%3D&reserved=0>

This error originated from a custom integration.

Logger: custom_components.navien_water_heater.navien_api
Source: custom_components/navien_water_heater/navien_api.py:242
Integration: Navien NaviLink Water Heater Integration (documentation)
First occurred: 19:42:32 (38609 occurrences)
Last logged: 20:29:17

ConnectionRefusedError: [Errno 111] Connect call failed ('52.23.151.44', 6001) This error occurred while attempting to reconnect to Navien server
TimeoutError: This error occurred while attempting to reconnect to Navien server

**Comment by nikshriv** [comment]
Just made a small update that should only check for reconnection every 15 seconds so it doesn’t clog up your HA server. Update through HACS

**Comment by alexruffell** [comment]
@nikshriv you are awesome! thank you

**Comment by nikshriv** [comment]
Should be up and running again. My Navilink connection was restored.
