### ISSUE TITLE
Navien Hot Button

### ISSUE THREAD

**Issue by Maverick766** [nikshriv/hass_navien_water_heater#9]
Hi, I've been using this integration for a while and it works great. The only thing I haven't been able to get to function is the hot button or some on demand button that I can use in an Automation to initiate a recirculation. Is this possible with the integration?

Thanks

**Comment by nikshriv** [comment]
It is definitely possible. Your water heater needs to be configured properly for the hot button to show up. This depends primarily on if the water heater recirculation settings are set for internal or external recirculation. You can change those settings by using the menu button on the water heater and selecting recirculation settings. Then you will need to select external recirculation, and then select Hot Button. You will then need to uninstall and reinstall the integration. Once you do so, the Hot Button entity will be created.
